disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  - type_body_length
  - file_length
  - function_body_length

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - fallthrough
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

excluded:
  - .build
  - Package.swift

reporter: xcode
