codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 2%
      weakup-core:
        paths:
          - "Sources/WeakupCore/**"
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 70%
        threshold: 5%

# Component definitions for better reporting
component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
  individual_components:
    - component_id: weakup-core
      name: WeakupCore (Business Logic)
      paths:
        - Sources/WeakupCore/**

# Ignore test files and build artifacts
ignore:
  - "Tests/**"
  - ".build/**"
  - "**/*.generated.swift"

# Comment configuration for PRs
comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

# Flag management
flags:
  unit-tests:
    paths:
      - Sources/WeakupCore/
    carryforward: true
